Improve `bundle pristine` error if `BUNDLE_GEMFILE` does not exist
Previously it would crash calling a method on `nil`, like this:

```
/path/to/lib/bundler/cli/common.rb:97:in `ensure_all_gems_in_lockfile!': undefined method `specs' for nil:NilClass (NoMethodError)
  from /path/to/lib/bundler/cli/pristine.rb:10:in `run'
  from /path/to/lib/bundler/cli.rb:728:in `pristine'
  from /path/to/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  from /path/to/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  from /path/to/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  from /path/to/lib/bundler/cli.rb:30:in `dispatch'
  from /path/to/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  from /path/to/lib/bundler/cli.rb:24:in `start'
  from /path/to/exe/bundle:49:in `block in <top (required)>'
  from /path/to/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
  from /path/to/exe/bundle:37:in `<top (required)>'
  from /path/to/bin/bundle:23:in `load'
  from /path/to/bin/bundle:23:in `<main>'
```

Now it shows the more meaningful

```
/path/to/wrong/gemfile not found
```