Auto merge of #6688 - voxik:check-search, r=colby-swandale
Check if 'search' is initialized.

The search was checked previously, so maybe it should be checked also at this place.

This issue was identified by Coverity scanner:

~~~
Error: FORWARD_NULL (CWE-476):
rubygem-bundler-1.16.1/usr/share/gems/gems/bundler-1.16.1/lib/bundler/lazy_specification.rb:77: null_check: Comparing "search" to a null-like value implies that "search" might be null-like.
rubygem-bundler-1.16.1/usr/share/gems/gems/bundler-1.16.1/lib/bundler/lazy_specification.rb:83: property_access: Accessing a property of null-like value "search".
#   81|             search = source.specs.search(self).last
#   82|           end
#   83|->         search.dependencies = dependencies if search.is_a?(RemoteSpecification) || search.is_a?(EndpointSpecification)
#   84|           search
#   85|         end
~~~

(cherry picked from commit 0aa5ea78c0d6cc1b843aeab603182c0d301203f2)