Improve usage messages
When POSIXLY_CORRECT environment variable is set, the argument parsing
tries to behave in POSIX-compatible manner. That is fine, but leads to
usage messages no longer being accurate:

    $ POSIXLY_CORRECT= gem open foo -e nano
    ERROR:  While executing gem ... (Gem::CommandLineError)
        Too many gem names (foo, -e, nano); please specify only one

Correct invocation would be:

    $ POSIXLY_CORRECT= gem open -e nano foo
    Unable to find gem 'foo'

However, usage help says nothing about that. This commit therefore
shuffles the usage order to make it always correct.