Make "gem cert --help" available when OpenSSL is missing
The entire Gem::Commands::CertCommand class is undefined when OpenSSL
is not available. This is not expected by Gem::CommandManager and
attempting to invoke the cert command fails with an unfriendly message:

	$ gem cert --help
	ERROR:  Loading command: cert (NameError)
		uninitialized constant Gem::Commands::CertCommand
	ERROR:  While executing gem ... (NoMethodError)
	    undefined method `deprecated?' for nil:NilClass

Let's tweak the OptionParser construction to not use OpenSSL constants
until they are necessary.