URI::Generic#hostname isn't needed here since the URIs aren't IPv6.
I don't see a need to break pre-1.9.3 rubies for this.

On ruby 1.9.2, this script fails:
```
util/update_bundled_ca_certificates.rb:13:in `connect_to': undefined method `hostname' for #<URI::HTTPS:0x007fc6d5885ec0 URL:https://rubygems.org> (NoMethodError)
```

This tool was added here: 82ed63eb599e0854