Improve conflict messaging
RubyGems now has improved output for dependency conflicts:

    $ ruby -Ilib bin/gem install my_gem -i ~/tmp/gems
    ERROR:  While executing gem ... (Gem::ImpossibleDependenciesError)
        rye-0.9.8 requires net-ssh (>= 2.0.13) but it conflicted:
      Activated net-ssh-2.6.7 instead of (~> 2.2.2) via:
        vagrant-1.0.7, my_gem2-0, my_gem-0
      Activated net-ssh-2.2.2 instead of (>= 2.6.5) via:
        net-scp-1.1.1, rye-0.9.8, my_gem-0

Now the dependency and its requirement are printed along with the nature
of the conflict and the path taken that resulted in the conflict.

Fixes #485