Raise a specific error for gemspecs with invalid dependencies
The idea is to get ready for removing the catch-all rescue during gem
installation, and limit it to a specific list of exceptions going
forward. By raising a specific exception here, instead of the original

```
NoMethodError: undefined method `type' for ["ruby-ajp", ">= 0.2.0"]:Array
```

we make sure we won't swallow other potential `NoMethodError`'s that
would be potential bugs in bundler.