Fetch gem to proper cache dir when gem path is not gem home
This fixes the pristine installation error for a gem that is installed
to other GEM PATH than $GEM_HOME and the cache file for that gem is
missing.

Example scenario:

```
$ cat ~/.gemrc
---
:sources:
- https://rubygems.org/
gem: --no-ri --no-rdoc
gempath:
- /Users/tkareine/gem-repo

$ gem env
RubyGems Environment:
  ...
  - INSTALLATION DIRECTORY: /Users/tkareine/.gem/ruby/1.9.3
  ...
  - GEM PATHS:
     - /Users/tkareine/.gem/ruby/1.9.3
     - /Users/tkareine/gem-repo
  ...

$ gem install -i ~/gem-repo timecop
Fetching: timecop-0.7.1.gem (100%)
Successfully installed timecop-0.7.1
1 gem installed

$ rm gem-repo/cache/timecop-0.7.1.gem
```

Without the fix we get an error:

```
$ gem pristine timecop
Restoring gems to pristine condition...
Cached gem for timecop-0.7.1 not found, attempting to fetch...
Fetching: timecop-0.7.1.gem (100%)
ERROR:  While executing gem ... (Gem::InstallError)
    invalid gem: No such file or directory - /Users/tkareine/gem-repo/cache/timecop-0.7.1.gem
```

With the fix:

```
$ gem pristine timecop
Restoring gems to pristine condition...
Cached gem for timecop-0.7.1 not found, attempting to fetch...
Fetching: timecop-0.7.1.gem (100%)
Restored timecop-0.7.1
```