Use 9.2.11.0 in warbler's realworld test case
The test passes on 9.2.9.0, breaks on 9.2.10, and passes again on
9.2.11.1.

Crash is like the following:

```
LoadError: no such file to load -- bundler/shared_helpers
  require at org/jruby/RubyKernel.java:974
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
   <main> at uri:classloader:/META-INF/init.rb:21
  require at org/jruby/RubyKernel.java:974
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:54
   <main> at <script>:2
ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- bundler/shared_helpers
```

It happens against the current default branch, and I don't know why it
happens.

Whatever it was, it seems fixed in jruby-9.2.11.1, so let's forget about
it.