Auto merge of #1873 - Fryguy:fix_query_command_with_exact, r=segiddins
Fix broken --exact parameter to gem command

# Description:

Before this patch `gem list --exact` fails with the following error:

    > gem list --exact aws-sdk

    *** LOCAL GEMS ***

    ERROR:  While executing gem ... (TypeError)
        type mismatch: String given

# Tasks:

- [x] Describe the problem / feature
- [x] Write tests
- [x] Write code to solve the problem
- [x] Get code review from coworkers / friends

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

(cherry picked from commit 9da1964c1df1680254d0f50954e0508c76458db2)