Fix another test issue detected by ruby-core
Some ruby-core jobs don't go through `rake` when testing rubygems. It
turns out `rake` requires `set`, and was making these `to_set` calls
actually work even though `rubygems` no longer requires `set` by
default. But since this does not happen in those ruby-core jobs, this
test was failing like this:

```
  1) Error:
TestGemUtil#test_glob_files_in_dir:
NoMethodError: undefined method `to_set' for ["/home/deivid/Code/rubygems/rubygems/tmp/test_rubygems_89987/g/h.rb", "/home/deivid/Code/rubygems/rubygems/tmp/test_rubygems_89987/g/i.rb"]:Array
Did you mean?  to_s
    /home/deivid/Code/rubygems/rubygems/test/rubygems/test_gem_util.rb:75:in `test_glob_files_in_dir'
```

I opened a PR to `rake` to avoid loading `set` unnecessarily and changed
the test to not use `set`.