Merge #2914
2914: Fix gem pristine not accounting for user installed gems r=bronzdoc a=bronzdoc

# Description:
closes https://github.com/rubygems/rubygems/issues/1968

The problem is gem pristine is always checking for the `INSTALLATION DIRECTORY` instead of the `USER INSTALLATION DIRECTORY` even if a gem is installed using the `--user-install` flag.

If a `INSTALLATION DIRECTORY` is not writable it would cause an error like:

```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.3.0 directory.
```

This check is not needed in the pristine command, writable gem_home directory is already being checked at installation time by `Gem::Installer#pre_install_checks`
______________

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).


Co-authored-by: bronzdoc <lsagastume1990@gmail.com>