Properly Handle Optional gemspec fields
required_ruby_version and required_rubygems_version are recommended, but optional fields in the [gemspec specification](https://guides.rubygems.org/specification-reference/#required_ruby_version).  Currently, lazy_specification and spec_group throw exceptions if they encounter gem specifications that do not have these set.

We have some really old private gems that do not set required_ruby_version in its spec so we are running into this after we bump past bundler `2.3.4`

Top part of lazy_specification stack trace
```
NoMethodError: undefined method `satisfied_by?' for nil:NilClass
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/lazy_specification.rb:94:in `block in __materialize__'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/lazy_specification.rb:92:in `select'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/lazy_specification.rb:92:in `__materialize__'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/spec_set.rb:75:in `block in materialize'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/spec_set.rb:72:in `map!'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/spec_set.rb:72:in `materialize'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/definition.rb:468:in `materialize'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/definition.rb:190:in `specs'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/installer.rb:243:in `ensure_specs_are_compatible!'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/installer.rb:83:in `block in run'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/process_lock.rb:9:in `open'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/process_lock.rb:9:in `lock'
  /usr/local/bundle/ruby/2.7.0/gems/bundler-2.3.11/lib/bundler/installer.rb:71:in `run'
  ```

```

Top part of the spec_group stack trace
```
NoMethodError: undefined method `none?' for nil:NilClass

unless spec.required_ruby_version.none?
                         ^^^^^^
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/resolver/spec_group.rb:101:in `metadata_dependencies'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/resolver/spec_group.rb:84:in `block in dependencies_for'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/resolver/spec_group.rb:83:in `map'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/resolver/spec_group.rb:83:in `dependencies_for'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/resolver/spec_group.rb:26:in `block in initialize'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/resolver/spec_group.rb:51:in `dependencies_for_activated_platforms'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:105:in `dependencies_for'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:18:in `block in dependencies_for'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/delegates/specification_provider.rb:17:in `dependencies_for'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:809:in `block in group_possibilities'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:808:in `reverse_each'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:808:in `group_possibilities'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:796:in `locked_requirement_possibility_set'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:776:in `possibilities_for_requirement'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:761:in `push_state_for_requirements'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:696:in `attempt_to_filter_existing_spec'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:672:in `attempt_to_activate'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:254:in `process_topmost_state'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/resolution.rb:182:in `resolve'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/vendor/molinillo/lib/molinillo/resolver.rb:43:in `resolve'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:50:in `start'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/resolver.rb:24:in `resolve'
  /usr/local/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.19/lib/bundler/definition.rb:480:in `reresolve'
  ```