Fix tests in case of running each relative test file.
We should avoid using `__FILE__` in each `test_*` method, because a value of
`__FILE__` in the `test_*.rb` is different executed from between `rake test`
and `ruby -Ilib:test:bundler/lib test/path/to/test_*.rb`.

When running `rake test`, the value of `__FILE__` is the absolute path.
When running `ruby -Ilib:test:bundler/lib test/rubygems/test_foo.rb`, the value
of `__FILE__` is the relative path. Note that in the `test_*` method, the
working directory (`Dir.pwd`) is `/path/to/tmp/test_rubygems_*`.

```
$ ruby -Ilib:test:bundler/lib test/rubygems/test_gem_ext_cargo_builder.rb -n /test_build_staticlib/
...
Error: test_build_staticlib(TestGemExtCargoBuilder): Errno::ENOENT: No such file or directory @ rb_check_realpath_internal - /home/jaruga/var/git/rubygems/tmp/test_rubygems_20220328-1989428-x5pim5/test/rubygems/test_gem_ext_cargo_builder/rust_ruby_example
...
test/rubygems/test_gem_ext_cargo_builder.rb:27:in `setup_rust_gem'
...
```